const SITE_URL = 'https://rachaeljuzeler.com/';

// Navigation functionality
document.addEventListener('DOMContentLoaded', function() {
    // Handle navigation active states
    const navLinks = document.querySelectorAll('nav a');
    const currentPage = window.location.pathname.split('/').pop() || 'index.html';

    navLinks.forEach(link => {
        link.classList.remove('active');
        const linkHref = link.getAttribute('href');

        if (linkHref === currentPage ||
            (currentPage === '' && linkHref === 'index.html') ||
            (currentPage === 'index.html' && linkHref === 'index.html')) {
            link.classList.add('active');
        }
    });

    // Handle project page loading
    if (window.location.pathname.includes('project.html')) {
        loadProjectContent();
    }

    // Exact match: 'available-piece.html' also contains 'piece.html'
    if (currentPage === 'piece.html') {
        loadPieceContent();
    }

    // Load grid background images
    loadGridBackgroundImages();
});

// Project content loader
function loadProjectContent() {
    const urlParams = new URLSearchParams(window.location.search);
    const projectId = urlParams.get('id');

    if (!projectId) {
        window.location.href = 'index.html';
        return;
    }

    // Project data comes from project-data.js, generated by rachael_content_manager.py
    const projectData = window.projectData || {};

    const project = projectData[projectId];

    if (!project) {
        window.location.href = 'index.html';
        return;
    }

    updateProjectSeo(projectId, project);

    // Update page content
    document.getElementById('project-title').textContent = project.title || '';
    document.getElementById('project-subtitle').textContent = project.subtitle || '';

    // Format description with proper paragraph breaks (blank line = new paragraph)
    const descriptionElement = document.getElementById('project-description');
    const paragraphs = (project.description || '').split(/\n\s*\n/);
    descriptionElement.innerHTML = paragraphs.map(p => `<p>${escapeHtml(p).replace(/\n/g, '<br>')}</p>`).join('');

    // Projects with individual works (e.g. CHANDELIERS) show the hero plus a clickable grid
    const pieces = getProjectPieces(projectId);
    if (pieces.length) {
        renderProjectImages(project.folder, project.title, (project.images || []).slice(0, 1));
        renderPieceGrid(projectId, pieces);
        return;
    }

    // Prefer the image list from project-data.js; fall back to probing fixed names
    if (Array.isArray(project.images) && project.images.length) {
        renderProjectImages(project.folder, project.title, project.images);
    } else {
        loadProjectImages(project.folder, project.title);
    }
}

function buildAbsoluteUrl(path) {
    return new URL(path, SITE_URL).toString();
}

function setMeta(selector, content) {
    const element = document.querySelector(selector);
    if (element && content) {
        element.setAttribute('content', content);
    }
}

function setCanonical(href) {
    const canonical = document.querySelector('link[rel="canonical"]');
    if (canonical && href) {
        canonical.setAttribute('href', href);
    }
}

function getProjectImageUrl(folderName) {
    return buildAbsoluteUrl('images/rjuzeler.jpg');
}

function updateProjectSeo(projectId, project) {
    const projectUrl = buildAbsoluteUrl(`project.html?id=${projectId}`);
    const pageTitle = `${project.title} | Rachael Juzeler`;
    const description = (project.description || '').split('\n')[0].trim();
    const imageUrl = getProjectImageUrl(project.folder);

    document.title = pageTitle;
    setCanonical(projectUrl);
    setMeta('meta[name="description"]', description);
    setMeta('meta[property="og:title"]', pageTitle);
    setMeta('meta[property="og:description"]', description);
    setMeta('meta[property="og:url"]', projectUrl);
    setMeta('meta[property="og:image"]', imageUrl);
    setMeta('meta[name="twitter:title"]', pageTitle);
    setMeta('meta[name="twitter:description"]', description);
    setMeta('meta[name="twitter:image"]', imageUrl);

    const structuredData = document.getElementById('project-structured-data');
    if (structuredData) {
        structuredData.textContent = JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'VisualArtwork',
            name: project.title,
            description,
            url: projectUrl,
            image: imageUrl,
            artMedium: project.subtitle,
            creator: {
                '@type': 'Person',
                name: 'Rachael Juzeler',
                url: buildAbsoluteUrl('')
            }
        });
    }
}

function escapeHtml(text) {
    return String(text)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}

// Render the images listed in project-data.js: first entry is the hero, rest go to the gallery
function renderProjectImages(folderName, projectTitle, imageNames) {
    const mainImageContainer = document.getElementById('project-main-image');
    const gallery = document.getElementById('project-gallery');

    mainImageContainer.innerHTML = '';
    gallery.innerHTML = '';

    imageNames.forEach((imageName, index) => {
        const img = document.createElement('img');
        img.src = `images/${encodeURIComponent(folderName)}/${encodeURIComponent(imageName)}`;
        img.alt = index === 0 ? `${projectTitle} - Main Image` : `${projectTitle} - ${imageName}`;
        img.style.opacity = '0';
        img.onload = function() {
            this.style.transition = 'opacity 0.5s ease';
            this.style.opacity = '1';
        };
        img.onerror = function() {
            this.remove();
        };

        if (index === 0) {
            mainImageContainer.appendChild(img);
        } else {
            img.className = 'project-image';
            gallery.appendChild(img);
        }
    });
}

// Individual works inside a project come from project-pieces-data.js (admin_data/project_pieces.json)
function getProjectPieceEntry(projectId) {
    const all = window.projectPieces || {};
    return all[projectId] || null;
}

function getProjectPieces(projectId) {
    const entry = getProjectPieceEntry(projectId);
    return entry && Array.isArray(entry.pieces) ? entry.pieces : [];
}

function getPieceImagePath(projectId, piece, imageName) {
    const entry = getProjectPieceEntry(projectId) || {};
    return `images/${encodeURIComponent(entry.image_dir || projectId)}/${encodeURIComponent(piece.folder || piece.id)}/${encodeURIComponent(imageName)}`;
}

function getPieceUrl(projectId, piece) {
    return `piece.html?project=${encodeURIComponent(projectId)}&id=${encodeURIComponent(piece.id)}`;
}

// Same card markup as the Available page so the grid looks and behaves the same
function renderPieceGrid(projectId, pieces) {
    const grid = document.getElementById('project-pieces');
    const gallery = document.getElementById('project-gallery');
    if (!grid) {
        return;
    }

    gallery.innerHTML = '';
    gallery.hidden = true;
    grid.innerHTML = '';
    grid.hidden = false;

    pieces.forEach(piece => {
        const card = document.createElement('article');
        card.className = 'available-card';

        const link = document.createElement('a');
        link.className = 'available-card-link';
        link.href = getPieceUrl(projectId, piece);
        link.setAttribute('aria-label', `View work: ${piece.title}`);

        const imageWrap = document.createElement('div');
        imageWrap.className = 'available-card-image-wrap';

        const image = document.createElement('img');
        image.className = 'available-card-image';
        image.alt = piece.title;
        image.loading = 'lazy';
        image.src = (piece.images || []).length
            ? getPieceImagePath(projectId, piece, piece.images[0])
            : 'images/rjuzeler.jpg';
        image.onerror = function() {
            this.onerror = null;
            this.src = 'images/rjuzeler.jpg';
        };
        imageWrap.appendChild(image);

        const textWrap = document.createElement('div');
        textWrap.className = 'available-card-text';

        const title = document.createElement('h2');
        title.className = 'available-card-title';
        title.textContent = piece.title;
        textWrap.appendChild(title);

        if (piece.year) {
            const year = document.createElement('p');
            year.className = 'available-card-price';
            year.textContent = piece.year;
            textWrap.appendChild(year);
        }

        link.appendChild(imageWrap);
        link.appendChild(textWrap);
        card.appendChild(link);
        grid.appendChild(card);
    });
}

// Detail page for one work: piece.html?project=project3&id=<piece id>
function loadPieceContent() {
    const params = new URLSearchParams(window.location.search);
    const projectId = params.get('project');
    const pieceId = params.get('id');
    const project = (window.projectData || {})[projectId];
    const piece = getProjectPieces(projectId).find(item => item.id === pieceId);

    const backLink = document.getElementById('piece-back-link');
    if (project) {
        backLink.href = `project.html?id=${encodeURIComponent(projectId)}`;
        backLink.textContent = `Back to ${project.title}`;
    }

    if (!piece) {
        document.getElementById('piece-missing').hidden = false;
        return;
    }

    document.getElementById('piece-detail').hidden = false;
    document.getElementById('piece-title').textContent = piece.title;

    [['piece-year', piece.year], ['piece-medium', piece.medium], ['piece-size', piece.size]].forEach(([id, value]) => {
        const element = document.getElementById(id);
        element.textContent = value || '';
        element.hidden = !value;
    });

    const description = document.getElementById('piece-description');
    description.innerHTML = '';
    (piece.description || '').split(/\n\s*\n/).filter(text => text.trim()).forEach(text => {
        const paragraph = document.createElement('p');
        paragraph.textContent = text.trim();
        description.appendChild(paragraph);
    });

    const images = piece.images || [];
    const mainImagePath = images.length ? getPieceImagePath(projectId, piece, images[0]) : 'images/rjuzeler.jpg';
    const mainImage = document.getElementById('piece-main-image');
    mainImage.alt = piece.title;
    mainImage.src = mainImagePath;

    const gallery = document.getElementById('piece-gallery');
    gallery.innerHTML = '';
    images.slice(1).forEach((imageName, index) => {
        const thumb = document.createElement('img');
        thumb.className = 'available-piece-thumb';
        thumb.alt = `${piece.title} detail ${index + 1}`;
        thumb.loading = 'lazy';
        thumb.src = getPieceImagePath(projectId, piece, imageName);
        thumb.onerror = function() {
            this.remove();
        };
        gallery.appendChild(thumb);
    });

    updatePieceSeo(projectId, piece, mainImagePath);
}

function updatePieceSeo(projectId, piece, imagePath) {
    const pageUrl = buildAbsoluteUrl(getPieceUrl(projectId, piece));
    const pageTitle = `${piece.title} | Rachael Juzeler`;
    const description = (piece.description || '').split('\n')[0].trim() || `${piece.title} by Rachael Juzeler.`;
    const imageUrl = buildAbsoluteUrl(imagePath);

    document.title = pageTitle;
    setCanonical(pageUrl);
    setMeta('meta[name="description"]', description);
    setMeta('meta[property="og:title"]', pageTitle);
    setMeta('meta[property="og:description"]', description);
    setMeta('meta[property="og:url"]', pageUrl);
    setMeta('meta[property="og:image"]', imageUrl);
    setMeta('meta[name="twitter:title"]', pageTitle);
    setMeta('meta[name="twitter:description"]', description);
    setMeta('meta[name="twitter:image"]', imageUrl);

    const structuredData = document.getElementById('piece-structured-data');
    if (structuredData) {
        const data = {
            '@context': 'https://schema.org',
            '@type': 'VisualArtwork',
            name: piece.title,
            description,
            url: pageUrl,
            image: imageUrl,
            creator: {
                '@type': 'Person',
                name: 'Rachael Juzeler',
                url: buildAbsoluteUrl('')
            }
        };
        if (piece.medium) {
            data.artMedium = piece.medium;
        }
        if (piece.year) {
            data.dateCreated = piece.year;
        }
        structuredData.textContent = JSON.stringify(data);
    }
}

// Function to automatically load images from project folder
function loadProjectImages(folderName, projectTitle) {
    const mainImageContainer = document.getElementById('project-main-image');
    const gallery = document.getElementById('project-gallery');

    mainImageContainer.innerHTML = '';
    gallery.innerHTML = '';

    // Common image file extensions to try
    const imageExtensions = ['jpg', 'jpeg', 'png', 'webp', 'gif'];

    // Main image names (for hero image)
    const mainImageNames = ['main', 'primary', 'hero'];

    // Additional image names (for gallery)
    const galleryImageNames = [
        'detail-1',
        'detail-2',
        'detail-3',
        'detail-4',
        'detail-5',
        'process-1',
        'process-2',
        'installation',
        'overview',
        'close-up',
        'macro',
        'environment',
        'context'
    ];

    let mainImageLoaded = false;
    let galleryImageCount = 0;
    const maxGalleryImages = 8;

    // Load main hero image
    mainImageNames.forEach(imageName => {
        if (mainImageLoaded) return;

        imageExtensions.forEach(ext => {
            if (mainImageLoaded) return;

            const imagePath = `images/${folderName}/${imageName}.${ext}`;

            const testImg = new Image();
            testImg.onload = function() {
                if (!mainImageLoaded) {
                    // Create main image
                    const img = document.createElement('img');
                    img.src = imagePath;
                    img.alt = `${projectTitle} - Main Image`;

                    // Add loading animation
                    img.style.opacity = '0';
                    img.onload = function() {
                        this.style.transition = 'opacity 0.5s ease';
                        this.style.opacity = '1';
                    };

                    mainImageContainer.appendChild(img);
                    mainImageLoaded = true;
                }
            };

            testImg.src = imagePath;
        });
    });

    // Load gallery images
    galleryImageNames.forEach(imageName => {
        if (galleryImageCount >= maxGalleryImages) return;

        imageExtensions.forEach(ext => {
            if (galleryImageCount >= maxGalleryImages) return;

            const imagePath = `images/${folderName}/${imageName}.${ext}`;

            const testImg = new Image();
            testImg.onload = function() {
                if (galleryImageCount < maxGalleryImages) {
                    // Create gallery image
                    const img = document.createElement('img');
                    img.src = imagePath;
                    img.alt = `${projectTitle} - ${imageName}`;
                    img.className = 'project-image';

                    // Add loading animation
                    img.style.opacity = '0';
                    img.onload = function() {
                        this.style.transition = 'opacity 0.3s ease';
                        this.style.opacity = '1';
                    };

                    gallery.appendChild(img);
                    galleryImageCount++;
                }
            };

            testImg.src = imagePath;
        });
    });

    // Show placeholders if no images found after a delay
    setTimeout(() => {
        if (!mainImageLoaded) {
            const placeholder = document.createElement('div');
            placeholder.className = 'main-image-placeholder';
            placeholder.innerHTML = `
                <p>Main project image will appear here</p>
                <p>Add: images/${folderName}/main.png</p>
            `;
            mainImageContainer.appendChild(placeholder);
        }

        if (gallery.children.length === 0) {
            const placeholder = document.createElement('div');
            placeholder.className = 'image-placeholder';
            placeholder.innerHTML = `
                <p>Additional project images will be added soon.</p>
                <p>Expected location: images/${folderName}/</p>
                <p>Supported formats: JPG, PNG, WebP, GIF</p>
            `;
            gallery.appendChild(placeholder);
        }
    }, 1000);
}

// Smooth scrolling for internal links
document.addEventListener('click', function(e) {
    if (e.target.matches('a[href^="#"]')) {
        e.preventDefault();
        const target = document.querySelector(e.target.getAttribute('href'));
        if (target) {
            target.scrollIntoView({
                behavior: 'smooth',
                block: 'start'
            });
        }
    }
});

// Add loading animation for work items
function animateWorkItems() {
    const workItems = document.querySelectorAll('.work-item');

    const observer = new IntersectionObserver((entries) => {
        entries.forEach(entry => {
            if (entry.isIntersecting) {
                entry.target.style.animationPlayState = 'running';
            }
        });
    });

    workItems.forEach(item => {
        observer.observe(item);
    });
}

// Function to load background images for work grid items
function loadGridBackgroundImages() {
    const workItems = document.querySelectorAll('.work-item');
    const imagePaths = [
        'main.png', 'main.jpg', 'main.JPG', 'main.jpeg',
        'primary.png', 'primary.jpg', 'primary.jpeg',
        'hero.png', 'hero.jpg', 'hero.jpeg'
    ];

    workItems.forEach(item => {
        const projectId = item.getAttribute('data-project');
        if (!projectId) return;

        const projectFolder = projectId;
        const imageContainer = item.querySelector('.work-item-image');
        if (!imageContainer) return;

        let imageLoaded = false;
        let pathIndex = 0;

        function tryNextImage() {
            if (imageLoaded || pathIndex >= imagePaths.length) {
                if (!imageLoaded) {
                    // Show placeholder
                    imageContainer.style.backgroundColor = 'rgba(0, 0, 0, 0.1)';
                    imageContainer.style.border = '2px dashed rgba(0, 0, 0, 0.3)';
                    imageContainer.innerHTML = '<div style="display: flex; align-items: center; justify-content: center; height: 100%; color: rgba(0, 0, 0, 0.5); font-size: 0.9rem;">Image Coming Soon</div>';
                }
                return;
            }

            const imagePath = `images/${projectFolder}/${imagePaths[pathIndex]}`;
            const testImg = new Image();

            testImg.onload = function() {
                if (!imageLoaded) {
                    imageContainer.style.backgroundImage = `url('${imagePath}')`;
                    imageContainer.style.backgroundSize = 'cover';
                    imageContainer.style.backgroundPosition = 'center';
                    imageContainer.style.backgroundRepeat = 'no-repeat';
                    imageLoaded = true;
                }
            };

            testImg.onerror = function() {
                pathIndex++;
                tryNextImage();
            };

            testImg.src = imagePath;
        }

        tryNextImage();
    });
}

// Initialize animations when DOM is loaded
document.addEventListener('DOMContentLoaded', animateWorkItems);
